server:
  port: 1010
spring:
  application:
    name: brpg-config
#git保持配置
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://git.oschina.net/xiaojian1123/ypdy-brpgConfig.git
#          search-paths: /**
#          default-label:
#      label: master

#svn保持配置   必须显式声明profiles.active=subversion,不然还是用的git
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: http://192.168.0.118/svn/ABProject_Server/ABGame/config
          username: zhongxiaojian
          password: 123456
          search-paths: /**
          default-label:


#集群部署
eureka:
  instance:
#    ip-address: 192.168.0.124
    prefer-ip-address: true  #优先使用IP地址作为主机名的标识
  client:
    serviceUrl:
      defaultZone: http://192.168.0.118:1000/eureka,http://192.168.0.124:1000/eureka