spring:
  application:
    name: brpg-eureka

server:
  port: 1000
#  port: ${port}

eureka:
  instance:
    ip-address: 192.168.0.124
    prefer-ip-address: true  #优先使用IP地址作为主机名的标识
#    instance-id: ${spring.application.name}:${server.port}
    hostname: 192.168.0.124  #主机名
#    appname: brpg-eureka
    # 心跳检测与续约时间
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true  #是否将自身的实例信息注册到Eureka服务端(注册中心集群环境下需开启)
    fetch-registry: true  #是否从Euarka服务端获取注册信息(注册中心集群环境下需开启)
    service-url:
      defaultZone: http://192.168.0.118:1000/eureka
#      defaultZone: ${eureka.server}

  # 测试时关闭自我保护机制，保证不可用服务及时踢出
  server:
    enable-self-preservation: false


